#!/usr/bin/python
from subprocess import Popen, PIPE, call
import shlex

gcc_location = "/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/gcc-11.1.0-qyyagvftz5pgrbuxefahh273x5txjpml/bin/g++"
clang_location = "/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/llvm-12.0.0-fmx2razucqcja44det235qdbqelf2soi/bin/clang++"
nvcc_location = "/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/nvhpc-21.9-yiw3cngl4t4nwambluvyxdq2ctmgcmch/Linux_x86_64/21.9/compilers/bin/nvc++"

call(shlex.split(gcc_location + " -o gcc-offload-acc mains/gcc-offload.cpp -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/eigen-3.4.0-57ptt6xndy7fmu3f6w6uzuvgl74z56tx/include/eigen3  -O2 -fopenacc"))
call(shlex.split(gcc_location + " -o gcc-offload-acc-dbl mains/gcc-offload.cpp -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/eigen-3.4.0-57ptt6xndy7fmu3f6w6uzuvgl74z56tx/include/eigen3  -O2 -fopenacc -DNAME=dbl"))
call(shlex.split(gcc_location + " -o gcc-offload mains/gcc-offload.cpp -I  -O2 -fopenmp"))
call(shlex.split(clang_location + " -o clang-offload mains/clang-offload.cpp -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/eigen-3.4.0-57ptt6xndy7fmu3f6w6uzuvgl74z56tx/include/eigen3  -O2 -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/llvm-12.0.0-fmx2razucqcja44det235qdbqelf2soi/include/ -lcudart -L/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/nvhpc-21.9-yiw3cngl4t4nwambluvyxdq2ctmgcmch/Linux_x86_64/21.9/cuda/lib64 -ldl -lrt -pthreads --libomptarget-nvptx-bc-path=/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/llvm-12.0.0-fmx2razucqcja44det235qdbqelf2soi/lib/libomptarget-nvptx-cuda_102-sm_70.bc -Wl,-rpath,/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/llvm-12.0.0-fmx2razucqcja44det235qdbqelf2soi/lib -B /usr/bin"))
call(shlex.split(nvcc_location + " -o nvcc-offload mains/nvcc-offload.cu -Wall -Wextra -fast -acc -fopenmp -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/nvhpc-21.9-yiw3cngl4t4nwambluvyxdq2ctmgcmch/Linux_x86_64/21.9/math_libs/10.2/targets/x86_64-linux/include -lcublas -gpu=cc70"))
call(shlex.split(gcc_location + " -o gcc-offload-dbl mains/gcc-offload.cpp -I  -O2 -fopenmp -DNAME=dbl"))
call(shlex.split(clang_location + " -o clang-offload-dbl mains/clang-offload.cpp -fopenmp -fopenmp-targets=nvptx64-nvidia-cuda -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/eigen-3.4.0-57ptt6xndy7fmu3f6w6uzuvgl74z56tx/include/eigen3  -O2 -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/llvm-12.0.0-fmx2razucqcja44det235qdbqelf2soi/include/ -lcudart -L/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/nvhpc-21.9-yiw3cngl4t4nwambluvyxdq2ctmgcmch/Linux_x86_64/21.9/cuda/lib64 -ldl -lrt -pthreads --libomptarget-nvptx-bc-path=/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/llvm-12.0.0-fmx2razucqcja44det235qdbqelf2soi/lib/libomptarget-nvptx-cuda_102-sm_70.bc -Wl,-rpath,/nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/llvm-12.0.0-fmx2razucqcja44det235qdbqelf2soi/lib -B /usr/bin -DNAME=dbl"))
call(shlex.split(nvcc_location + " -o nvcc-offload-dbl mains/nvcc-offload.cu -Wall -Wextra -fast -acc -fopenmp -I /nfs/dust/atlas/user/maniageo/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/nvhpc-21.9-yiw3cngl4t4nwambluvyxdq2ctmgcmch/Linux_x86_64/21.9/math_libs/10.2/targets/x86_64-linux/include -lcublas -DNAME=dbl -gpu=cc70"))